apiVersion: apps/v1
kind: Deployment
metadata:
  name: relation-api-server
  labels:
    app: relation-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relation-api-server
  template:
    metadata:
      labels:
        app: relation-api-server
    spec:
      imagePullSecrets:
        - name: facegram-registery
      containers:
        - name: relation-api-server
          image: cr.fcgm.dev/facegram/relation_service:25865715
          ports:
            - containerPort: 8080
            - containerPort: 30018
          env:
            - name: NODE_ENV
              value: "dev"   
          envFrom:
            - secretRef:
                name: grpc-client-configs
            - secretRef:
                name: grpc-client-urls 
            - secretRef:
                name: sentry-credential
            - secretRef:
                name: arangodb-credential
            - secretRef:
                name: redis-credential 
            - secretRef:
                name: rabbitmq-credential 
            - secretRef:
                name: aes-keys                                                                          
